# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 43b0f4037a9101c6e36fbd1e4d3e0386cabe89313a458532d506cba67351e5f7e842239403b1575aba05338b012a47e289fbf46d29ba829aa28fdaba40cedcc2

test:
  secret_key_base: c65d14620ec6f0ed28ca68c5cd52fb07a522e8b194642ec0a4fe7cee3487bd563e1d9eb11672e7bb2e8b3c1b70ae96b574e53bc32fc700dfe385e170257d7120

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
